export const catchCallback = (error: any): void => {
  console.error(error, 'catch callback')
}
